# This script deploys your website automatically
name: CI

# Only trigger this script when you push to the master branch
on:
  push:
    branches: [ main ]

# Specify the tasks to run when this script gets triggered
jobs:
  build:
    runs-on: ubuntu-latest

    # Download our main branch
    steps:
    - uses: actions/checkout@v2
    - name: Build the static website
      run: npm run prod
    - name: Configure Git
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
    - name: Commit changes
      run: |
        cd dist
        git init
        git add .
        git commit -m "Deploy to gh-pages"
        cd ..
    # Run our deployment command
    - name: Deploying the static website to gh-pages
      run: npm run deploy
